# Root directory for all artifacts
artifacts_root: artifacts

# Configuration for data ingestion process
data_ingestion:
  root_dir: artifacts/data_ingestion # Directory to store the data ingestion artifacts
  source_URL: https://drive.google.com/file/d/10vW7LivNBhdVmNtQCsmmpNu6RYBw53RM/view?usp=sharing # URL to download the dataset
  local_data_file: artifacts/data_ingestion/data.zip # Local path to save the downloaded dataset
  unzip_dir: artifacts/data_ingestion # Directory to unzip the dataset

# Configuration for Model Preparatoin Stage
model_preparation:
  root_dir: artifacts/model_preparation # Directory to store built model preparation artifacts
  built_model_path: artifacts/model_preparation/built_model.h5 # Path to save the built model

# Configuration for Model Training Stage
training:
  root_dir: artifacts/training # Directory to store training artifacts
  trained_model_path: artifacts/training/model.h5 # Path to save the trained model
