# Configuration for model parameters
  IMAGE_SIZE: [256, 256, 3]   # Ensure this matches the input shape/or/Image size of your model
  N_CLASSES: 4                # Number of output classes
  BATCH_SIZE: 32              # Number of samples per gradient update
  EPOCHS: 60                  # Number of epochs to train the model
  LEARNING_RATE: 0.001        # Learning rate for the optimizer
  RHO: 0.9                    # Optimizer rho
  EPSILON: 1e-08              # Optimizer Epsilon
  PATIENCE: 3                 # Learning Rate Annealer/Reduction (ReduceLROnPlateau) Parameter
  FACTOR: 0.5                 # ReduceLROnPlateau Parameter
  MIN_LR: 0.00001             # ReduceLROnPlateau Parameter
  VERPOSE: 1                  # ReduceLROnPlateau Parameter
